{% set name = "eden-kernel" %}
{% set version = "0.3.1350" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eden-kernel-{{ version }}.tar.gz
  sha256: 621a2d0a0a8b5bc758f453d53d25dc7aac091e18cb623a097349dc84acde23dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dill
    - future
    - python >=3.8
    - joblib
    - matplotlib-base
    - networkx >=2.0
    - numpy >=1.10.4
    - requests
    - scikit-learn >=0.18.2
    - scipy >=0.14.0
    - toolz

test:
  imports:
    - eden
    - eden.display
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fabriziocosta/EDeN
  summary: Explicit Decomposition with Neighborhoods
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
